### PR TITLE
feature: add LocalTime scalar

### PR DESCRIPTION
**Pull request by setchy**
Accompanies changes in https://github.com/Netflix/dgs-framework/pull/1008, which addresses https://github.com/Netflix/dgs-framework/issues/953

### CODE REVIEW

**Comment by srinivasankavitha** [comment]
Looks good, will merge this PR once the changes are released.

**Comment by setchy** [comment]
@srinivasankavitha - fixed the merge conflicts

**Comment by setchy** [comment]
Released in v4.10.0

**Comment by setchy** [comment]
@srinivasankavitha would you be so kind as to merge this PR when you get a moment

**Review by berngp — APPROVED** [review]

**Pull request merged**
